# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-angle.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-angle.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-angle.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-angle.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/string-functions/concat-ws.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/string-functions/concat-ws.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/string-functions/concat-ws.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/string-functions/concat-ws.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/string-functions/concat-ws.md  

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-angle-sphere.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-angle-sphere.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-angle-sphere.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-angle-sphere.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-angle-sphere.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-area-square-km.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-area-square-km.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-area-square-km.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-area-square-km.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-area-square-km.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-area-square-km.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-meters.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-meters.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-area-square-km.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-km.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-area-square-km.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-meters.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-area-square-meters.md


# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-asbinary
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-asbinary
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-asbinary
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-asbinary
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-asbinary.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-astext.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-astext.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-astext.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-astext.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-astext.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-azimuth.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-azimuth.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-azimuth.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md/mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-azimuth.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-azimuth.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-circle.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-circle.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-circle.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-circle.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-circle.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-contains.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-contains.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-contains.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-contains.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-contains.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-disjoint.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-disjoint.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-disjoint.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-disjoint.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-disjoint.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-distance-sphere.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-distance-sphere.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md

# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.0/sql-manual/sql-functions/spatial-functions/st-distance-sphere.md
# # cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-1.2/sql-manual/sql-functions/spatial-functions/st-distance-sphere.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-distance-sphere.md


# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromtext.md

# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromwkb.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromwkb.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromwkb.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-geometryfromwkb.md

# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-intersects.md


# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-linefromtext.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-linefromtext.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-linefromtext.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-linefromtext.md


# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-point.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-point.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-point.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-point.md


# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-polygon.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-polygon.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-polygon.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-polygon.md


# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-touches.md


# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-x.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-x.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-x.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-x.md

# cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md
# cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/spatial-functions/st-y.md



cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/convert-tz.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/convert-tz.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/convert-tz.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/convert-tz.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/convert-tz.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/convert-tz.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/convert-tz.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/convert-tz.md

cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/curdate.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/curdate.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/curdate.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/curdate.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/curdate.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/curdate.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/curdate.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/curdate.md


cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/unix-timestamp.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/unix-timestamp.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/unix-timestamp.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/unix-timestamp.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/unix-timestamp.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/unix-timestamp.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/unix-timestamp.md /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/unix-timestamp.md

cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-add.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-add.md 
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-add.md  /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date-add.md 
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-add.md  /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-add.md 
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-add.md  /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date-add.md 

cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md  /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md  /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md  /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date-ceil.md

cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md  /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md  /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md  /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date-floor.md

cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-format.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-format.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-format.md  /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date-format.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-format.md  /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-format.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-format.md  /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date-format.md

cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-sub.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-sub.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-sub.md  /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date-sub.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-sub.md  /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-sub.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-sub.md  /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date-sub.md

cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md  /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md  /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date-trunc.md

cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date.md  /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/date.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date.md /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/date.md
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/date.md  /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/date.md

cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/datediff.md /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/datediff.md 
cp /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/datediff.md  /mnt/disk5/jianhao/jianhao/work/doris-website/i18n/zh-CN/docusaurus-plugin-content-docs/current/sql-manual/sql-functions/scalar-functions/date-time-functions/datediff.md 
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/datediff.md  /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-2.1/sql-manual/sql-functions/scalar-functions/date-time-functions/datediff.md 
cp /mnt/disk5/jianhao/jianhao/work/doris-website/versioned_docs/version-3.0/sql-manual/sql-functions/scalar-functions/date-time-functions/datediff.md   /mnt/disk5/jianhao/jianhao/work/doris-website/docs/sql-manual/sql-functions/scalar-functions/date-time-functions/datediff.md 

