{
 "title": "Default Custom Doris Cloud Dashboard Overview",
 "description": "Default Custom Dashboard for Doris Cloud",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster_id", "query": { "query": "label_values(up, job)" } },
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(up{job=\"$cluster_id\"},cluster_name)"
    }
   },
   {
    "name": "fe_master",
    "query": {
     "query": "query_result(node_info{group=\"fe\", job=\"$cluster_id\", type=\"is_master\"})"
    }
   },
   {
    "name": "fe_instance",
    "query": {
     "query": "up{group=\"fe\", job=\"$cluster_id\"}"
    }
   },
   {
    "name": "compute_group",
    "query": {
     "query": "up{group=\"be\", compute_group!=\"\", job=\"$cluster_id\"}"
    }
   },
   {
    "name": "be_instance",
    "query": {
     "query": "up{group=\"be\", compute_group=~\"$compute_group\", job=\"$cluster_id\"}"
    }
   },
   {
    "name": "brpc_instance",
    "query": {
     "query": "up{group=\"be-brpc\", compute_group=~\"$compute_group\", job=\"$cluster_id\"}"
    }
   },
   {
    "name": "node_exporter_group",
    "query": "(cluster-node-exporter|fe-node-exporter|be-node-exporter),(cluster-node-exporter|fe-node-exporter),(cluster-node-exporter|be-node-exporter)"
   }
  ]
 },
 "panels": [
  {
   "title": "[Example] Custom Cluster Overview Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "cluster_name",
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(doris_fe_table_data_size{job=\"$cluster_id\"}) / count(up{group=\"fe\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "Data size per table",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (db_name, table_name) (doris_fe_table_data_size{job=\"$cluster_id\"})",
     "legendFormat": "{{db_name}}:{{table_name}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "description": "Queries per seconds on each Frontends.\nQueries only include Select requests.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "format": "time_series",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(doris_fe_query_total{job=\"$cluster_id\", group=\"fe\", instance=~\"$fe_instance\", user=\"\", cluster_id=\"\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "99th Latency",
   "type": "graph",
   "description": "99 quantiles of query latency on each Frontends.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max by (instance) (doris_fe_query_latency_ms{job=\"$cluster_id\", quantile=\"0.99\", group=\"fe\", instance=~\"$fe_instance\", user=\"\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FE Cache Hit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "format": "time_series",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "doris_fe_cache_hit{job=\"$cluster_id\", group=\"fe\", instance=~\"$fe_instance\", type=\"partition\"}",
     "legendFormat": "partition-{{instance}}"
    },
    {
     "expr": "doris_fe_cache_hit{job=\"$cluster_id\", group=\"fe\", instance=~\"$fe_instance\", type=\"sql\"}",
     "legendFormat": "sql-{{instance}}"
    }
   ]
  },
  {
   "title": "BE File Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "format": "time_series",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(doris_be_num_io_bytes_read_from_cache{job=\"$cluster_id\", group=\"be\", compute_group=~\"$compute_group\", name=~\".*\"}[$__rate_interval])) / (sum by (instance) (rate(doris_be_num_io_bytes_read_total{job=\"$cluster_id\", group=\"be\",compute_group=~\"$compute_group\", name=~\".*\"}[$__rate_interval])) + 1e-10)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BE Cache Read MB/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "format": "time_series",
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "sum(doris_be_disk_bytes_read{job=\"$cluster_id\", compute_group=~\"$compute_group\", instance=~\"$be_instance\", device=~\".*\"}) by (job, instance) / sum(doris_be_disk_read_time_ms{job=\"$cluster_id\", compute_group=~\"$compute_group\", instance=~\"$be_instance\", device=~\".*\"}) by (job, instance) / 1048576 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "BE Cache Write MB/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "format": "time_series",
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "sum(doris_be_disk_bytes_written{job=\"$cluster_id\", compute_group=~\"$compute_group\", instance=~\"$be_instance\", device=~\".*\"}) by (job, instance) / sum(doris_be_disk_read_time_ms{job=\"$cluster_id\", compute_group=~\"$compute_group\", instance=~\"$be_instance\", device=~\".*\"}) by (job, instance) / 1048576 ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "[Example] Custom Machines Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - sum by(job, instance) (rate(node_cpu_seconds_total{job=\"$cluster_id\",mode=\"idle\",group=~\"$node_exporter_group\"}[$__rate_interval])) / sum by(job, instance) (rate(node_cpu_seconds_total{job=\"$cluster_id\",group=~\"$node_exporter_group\"}[$__rate_interval])) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Used Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by (instance, mountpoint) (100 - (node_filesystem_avail_bytes{fstype!~\"rootfs|tmpfs|devtmpfs|proc|sysfs|cgroup|bpf\",job=\"$cluster_id\",mountpoint=~\".*\",group=~\"$node_exporter_group\"} * 100) / (node_filesystem_size_bytes{fstype!~\"rootfs|tmpfs|devtmpfs|proc|sysfs|cgroup|bpf\",job=\"$cluster_id\",mountpoint=~\".*\",group=~\"$node_exporter_group\"}))",
       "legendFormat": "{{instance}}-{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Mem Used Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(job, instance) (node_memory_MemTotal_bytes{job=\"$cluster_id\",group=~\"$node_exporter_group\"} - node_memory_MemFree_bytes{job=\"$cluster_id\",group=~\"$node_exporter_group\"} - node_memory_Cached_bytes{job=\"$cluster_id\",group=~\"$node_exporter_group\"} - node_memory_Buffers_bytes{job=\"$cluster_id\",group=~\"$node_exporter_group\"} - node_memory_SReclaimable_bytes{job=\"$cluster_id\",group=~\"$node_exporter_group\"}) / sum by(job, instance) (node_memory_MemTotal_bytes{job=\"$cluster_id\",group=~\"$node_exporter_group\"}) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[Example] Custom FE Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Max Replayed Journal ID",
     "type": "graph",
     "description": "The max replayed meta data journal id on Frontends.\nNormally, all Frontends should be same on this metrics, or just slightly different for a short period.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "doris_fe_max_journal_id{job=\"$cluster_id\", group=\"fe\", instance=~\"$fe_instance\", cluster_id=\"\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Edit Log Size",
     "type": "graph",
     "description": "The edit log size for each FE",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "doris_fe_edit_log{job=\"$cluster_id\"}",
       "legendFormat": "{{instance}}-{{type}}"
      }
     ]
    },
    {
     "title": "Image Clean",
     "type": "graph",
     "description": "The image clean of each FE",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "doris_fe_image_clean{job=\"$cluster_id\", type=\"success\"}",
       "legendFormat": "{{instance}}_success"
      },
      {
       "expr": "doris_fe_image_clean{job=\"$cluster_id\", type=\"failed\"}",
       "legendFormat": "{{instance}}_failed"
      }
     ]
    }
   ]
  },
  {
   "title": "[Example] Custom BE Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "BE FD Count",
     "type": "graph",
     "description": "The file descriptor usage of Backends. Left Y axes shows the used fd num. Right Y axes shows the soft limit open file number.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_be_process_fd_num_used{job=\"$cluster_id\", group=\"be\", compute_group=~\"$compute_group\", instance=~\"$be_instance\"}",
       "legendFormat": "{{instance}}-used"
      },
      {
       "expr": "doris_be_process_fd_num_limit_soft{job=\"$cluster_id\", group=\"be\", compute_group=~\"$compute_group\", instance=~\"$be_instance\"}",
       "legendFormat": "{{instance}}-soft limit"
      }
     ]
    },
    {
     "title": "BE Thread Num",
     "type": "graph",
     "description": "The thread number of Backends",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "doris_be_process_thread_num{job=\"$cluster_id\", group=\"be\", compute_group=~\"$compute_group\", instance=~\"$be_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Tablet Distribution",
     "type": "graph",
     "description": "Number of tablets of each Backends",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "doris_fe_tablet_num{job=\"$cluster_id\"}",
       "legendFormat": "{{backend}}-backend"
      }
     ]
    }
   ]
  },
  {
   "title": "[Example] Custom Brpc Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bthread Timer Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "bthread_timer_usage{job=\"$cluster_id\", group=\"be-brpc\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bthread Worker Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "bthread_worker_usage{job=\"$cluster_id\", group=\"be-brpc\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[Example] Custom Meta Service Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "get_tablet_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_doris_cloud_meta_service_get_tablet_qps\", job=\"$cluster_id\", group=\"meta_service\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "{__name__=~\"rpc_server_.*_selectdb_meta_service_get_tablet_qps\", job=\"$cluster_id\", group=\"meta_service\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "tablet_job_qps",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "{__name__=~\"rpc_server_.*_doris_cloud_meta_service_finish_tablet_job_qps\",job=\"$cluster_id\", group=\"meta_service\"}",
       "legendFormat": "finish-job-{{instance}}"
      },
      {
       "expr": "{__name__=~\"rpc_server_.*_selectdb_meta_service_finish_tablet_job_qps\", job=\"$cluster_id\", group=\"meta_service\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "[Example] Custom Remote Storage Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "file cache element count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\".*_file_cache_normal_queue_element_count\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}-{{__name__}}-data"
      },
      {
       "expr": "{__name__=~\".*_file_cache_index_queue_element_count\",job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}--{{__name__}}-index"
      },
      {
       "expr": "{__name__=~\".*_file_cache_disposable_queue_element_count\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}--{{__name__}}-disposable"
      },
      {
       "expr": "{__name__=~\".*_file_cache_ttl_element_count\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}--{{__name__}}-ttl"
      }
     ]
    },
    {
     "title": "file cache evict rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(label_replace({__name__=~\".*_file_cache_total_evict_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}, \"name_label\", \"$1\",\"__name__\", \"(.+)\")[$__rate_interval:])",
       "legendFormat": "{{instance}}-total"
      },
      {
       "expr": "irate(label_replace({__name__=~\".*_file_cache_normal_queue_evict_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}, \"name_label\", \"$1\",\"__name__\", \"(.+)\")[$__rate_interval:])",
       "legendFormat": "{{instance}}-normal"
      },
      {
       "expr": "irate(label_replace({__name__=~\".*_file_cache_index_queue_evict_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}, \"name_label\", \"$1\",\"__name__\", \"(.+)\")[$__rate_interval:])",
       "legendFormat": "{{instance}}-index"
      },
      {
       "expr": "irate(label_replace({__name__=~\".*_file_cache_disposable_queue_evict_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}, \"name_label\", \"$1\",\"__name__\", \"(.+)\")[$__rate_interval:])",
       "legendFormat": "{{instance}}-disposable"
      },
      {
       "expr": "irate(label_replace({__name__=~\".*_file_cache_ttl_cache_evict_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}, \"name_label\", \"$1\",\"__name__\", \"(.+)\")[$__rate_interval:])",
       "legendFormat": "{{instance}}-ttl"
      }
     ]
    },
    {
     "title": "file cache data size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "{__name__=~\".*_file_cache_cache_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}-{{__name__}}-total"
      },
      {
       "expr": "{__name__=~\".*_file_cache_normal_queue_cache_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}-normal"
      },
      {
       "expr": "{__name__=~\".*_file_cache_index_queue_cache_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}-{{__name__}}-index"
      },
      {
       "expr": "{__name__=~\".*_file_cache_disposable_queue_cache_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}-{{__name__}}-disposable"
      },
      {
       "expr": "{__name__=~\".*_file_cache_ttl_cache_size\", job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}-{{__name__}}-ttl"
      }
     ]
    },
    {
     "title": "s3_write_read_rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(s3_file_writer_bytes_written{job=\"$cluster_id\", instance=~\"$brpc_instance\"}[$__rate_interval])",
       "legendFormat": "write_rate-{{instance}}"
      },
      {
       "expr": "irate(s3_file_reader_bytes_read{job=\"$cluster_id\", instance=~\"$brpc_instance\"}[$__rate_interval])",
       "legendFormat": "read_rate-{{instance}}"
      }
     ]
    },
    {
     "title": "s3_write_read",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "s3_file_writer_bytes_written{job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{__name__}}-{{instance}}"
      },
      {
       "expr": "s3_file_reader_bytes_read{job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{__name__}}-{{instance}}"
      }
     ]
    },
    {
     "title": "load bytes downloaded from s3",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "targets": [
      {
       "expr": "buffered_reader_bytes_downloaded{job=\"$cluster_id\", instance=~\"$brpc_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[Example] Custom Fdb Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "fdb_data_total_disk_used_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fdb_data_total_disk_used_bytes{job=\"$cluster_id\", group=\"meta_service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "fdb_data_total_kv_size_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fdb_data_total_kv_size_bytes{job=\"$cluster_id\", group=\"meta_service\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}