name: Cron Generate Pdf

on: 
  schedule:
    - cron: '0 12,18,1 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          persist-credentials: false
          submodules: recursive

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.0

    - name: Generate PDF
      run: |
        npx vitpress-generate-pdf --initialDocURLs="https://doris.apache.org/zh-CN/docs/2.1/install/source-install/compilation-with-docker" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/static/doris_logo_512_4903556647.png" --coverTitle="Apache Doris v2.1 中文文档" --outputPDFFilename="Apache Doris v2.1 中文文档.pdf" --tocOnlyH1=true
        npx vitpress-generate-pdf --initialDocURLs="https://doris.apache.org/zh-CN/docs/2.0/install/source-install/compilation-with-docker" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/static/doris_logo_512_4903556647.png" --coverTitle="Apache Doris v2.0 中文文档" --outputPDFFilename="Apache Doris v2.0 中文文档" --tocOnlyH1=true
        npx vitpress-generate-pdf --initialDocURLs="https://doris.apache.org/zh-CN/docs/install/source-install/compilation-with-docker" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/static/doris_logo_512_4903556647.png" --coverTitle="Apache Doris v3.0 中文文档" --outputPDFFilename="Apache Doris v3.0 中文文档" --tocOnlyH1=true
        mkdir -p ./build-pdf/assets/files/
        cp *.pdf ./build-pdf/assets/files/
        ls ./build-pdf/assets/files/

    - name: Upload files to OSS
      uses: ./.github/actions/aliyun-oss-website-action
      with:
          accessKeyId: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.ALIYUN_OSS_BUCKET }}
          # use your own endpoint
          endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          folder: build-pdf
          onlyUpload: true
