name: Cron Generate Pdf

on: 
  schedule:
    - cron: '0 1 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          persist-credentials: false
          submodules: recursive

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.0

   - name: Generate PDF
      run: |
        mkdir -p ./build-pdf/assets/files/
        cp *.pdf ./build-pdf/assets/files/
        ls ./build-pdf/assets/files/


    - name: Upload files to OSS
      uses: ./.github/actions/aliyun-oss-website-action
      with:
          accessKeyId: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.ALIYUN_OSS_BUCKET }}
          # use your own endpoint
          endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          folder: build-pdf
          onlyUpload: true