name: Cron Generate PDF

on:
  schedule:
    - cron: '0 1 * * *'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  Generate-PDF:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          persist-credentials: false
          submodules: recursive

    - name: Add Chinese Fonts
      run: |
          sudo apt-get install ttf-mscorefonts-installer
          sudo apt-get install fontconfig
          fc-list :lang=zh
          ls -lh /usr/share/fonts/
          cp -rf ./static/fonts/* /usr/share/fonts/
          mkfontscale
          mkfontdir
          fc-cache
          fc-list :lang=zh

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.14.0
    
    - name: Generate PDF
      run: |
        npx vitpress-generate-pdf --initialDocURLs="https://doris.apache.org/docs/dev/get-starting/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/static/doris_logo_512_4903556647.png" --coverTitle="Apache Doris Docs (English)" --outputPDFFilename="Apache Doris Docs (English).pdf" --tocOnlyH1=true
        npx vitpress-generate-pdf --initialDocURLs="https://doris.apache.org/zh-CN/docs/dev/get-starting/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/static/doris_logo_512_4903556647.png" --coverTitle="Apache Doris Docs (中文)" --outputPDFFilename="Apache Doris Docs (中文).pdf" --tocOnlyH1=true
        ls
        rm -rf ./build/**
        mkdir -p ./build/assets/files/
        cp *.pdf ./build/assets/files/
        ls ./build/assets/files/

    - name: Upload files to OSS
      uses: ./.github/actions/aliyun-oss-website-action
      with:
          accessKeyId: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.ALIYUN_OSS_BUCKET }}
          endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          folder: build
