name: Generate PDF

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Specify the branch name'
        required: true
        default: 'master'
      doc_version:
        description: 'Generate PDF for doc version'
        required: true
        default: '1.1'
        type: "choice"
        options: 
          - "ALL"
          - "1.1"
          - "0.15"
          - "dev"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          persist-credentials: false
          submodules: recursive

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.14.0

    - name: Build
      run: |
        git clone https://github.com/apache/doris.git
        mkdir versioned_docs/version-dev/
        cp -R doris/docs/en/docs/* versioned_docs/version-dev/
        cp -R doris/docs/sidebars.json versioned_sidebars/version-dev-sidebars.json
        mkdir i18n/zh-CN/docusaurus-plugin-content-docs/version-dev
        cp -R doris/docs/zh-CN/docs/* i18n/zh-CN/docusaurus-plugin-content-docs/version-dev/
        cp -R doris/docs/dev.json i18n/zh-CN/docusaurus-plugin-content-docs/version-dev.json

        cp -R doris/docs/images static/
        npm install -g yarn
        yarn cache clean
        yarn && yarn build
        touch build/.dummy
        cp .asf-site.yaml ./build/.asf.yaml
        cp versions.json ./build/
        ls build
        export DORIS_COMMIT=`git rev-parse HEAD`
    
    - name: Generate All Versions PDF
      if: ${{ github.event.inputs.doc_version == 'ALL'}}
      run: |
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/docs/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris 1.1 (English)" --outputPDFFilename="Apache Doris 1.1 (English).pdf"
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/zh-CN/docs/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris 1.1 (中文)" --outputPDFFilename="Apache Doris 1.1 (中文).pdf"
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/docs/0.15/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris 0.15 (English)" --outputPDFFilename="Apache Doris 0.15 (English).pdf"
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/zh-CN/0.15/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris 0.15 (中文)" --outputPDFFilename="Apache Doris 0.15 (中文).pdf"
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/docs/dev/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris Dev (English)" --outputPDFFilename="Apache Doris Dev (English).pdf"
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/zh-CN/docs/dev/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris Dev (中文)" --outputPDFFilename="Apache Doris Dev (中文).pdf"
        mkdir -p ./build/assets/files/
        cp *.pdf ./build/assets/files/

    - name: Generate PDF version_1.1
      if: ${{ github.event.inputs.doc_version == '1.1'}}
      run: |
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/docs/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris 1.1 (English)" --outputPDFFilename="Apache Doris 1.1 (English).pdf"
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/zh-CN/docs/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris 1.1 (中文)" --outputPDFFilename="Apache Doris 1.1 (中文).pdf"
        mkdir -p ./build/assets/files/
        cp *.pdf ./build/assets/files/

    - name: Generate PDF version_0.15
      if: ${{ github.event.inputs.doc_version == '0.15'}}
      run: |
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/docs/0.15/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris 0.15 (English)" --outputPDFFilename="Apache Doris 0.15 (English).pdf"
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/zh-CN/0.15/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris 0.15 (中文)" --outputPDFFilename="Apache Doris 0.15 (中文).pdf"
        mkdir -p ./build/assets/files/
        cp *.pdf ./build/assets/files/

    - name: Generate PDF version_dev
      if: ${{ github.event.inputs.doc_version == 'dev'}}
      run: |
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/docs/dev/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris Dev (English)" --outputPDFFilename="Apache Doris Dev (English).pdf"
        npx vitpress-generate-pdf --buildDirPath="./build/"  --firstDocPath="/zh-CN/docs/dev/summary/basic-summary/" --paginationSelector=".pagination-nav__link--next" --contentSelector="article" --coverImage="https://cdn.selectdb.com/images/doris-logo-512.png" --coverTitle="Apache Doris Dev (中文)" --outputPDFFilename="Apache Doris Dev (中文).pdf"
        mkdir -p ./build/assets/files/
        cp *.pdf ./build/assets/files/

    - name: Upload files to OSS
      uses: ./.github/actions/aliyun-oss-website-action
      with:
          accessKeyId: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.ALIYUN_OSS_BUCKET }}
          # use your own endpoint
          endpoint: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          folder: build

    - name: Deploy Website
      if: ${{ github.event.inputs.branch == 'master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_branch: asf-site
        publish_dir: ./build
        destination_dir: ./
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Automated deployment with doris branch ${{ github.event.inputs.branch }}@${{ env.DORIS_COMMIT }}'
        
    - name: Deploy Branch
      if: ${{ github.event.inputs.branch != 'master' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: $GITHUB_TOKEN
        publish_branch: asf-site
        publish_dir: ./build
        destination_dir: ${{ github.event.inputs.branch }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Automated deployment with doris branch ${{ github.event.inputs.branch }}@${{ env.DORIS_COMMIT }}'
