# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive
      - uses: ./.github/actions/cspell-action
        with:
            # Define glob patterns to filter the files to be checked. Use a new line between patterns to define multiple patterns.
            # The default is to check ALL files that were changed in in the pull_request or push.
            # Note: `ignorePaths` defined in cspell.json still apply.
            # Example:
            # files: |
            #   **/*.{ts,js}
            #   !dist/**/*.{ts,js}
            #
            # Default: ALL files
            files: |
                blog/**/*.{md,json}
                docs/**/*.{md,json}
                i18n/zh-CN/**/*.{md,json}
                community/**/*.{md,json}
        
            # Check files and directories starting with `.`.
            # - "true" - glob searches will match against `.dot` files.
            # - "false" - `.dot` files will NOT be checked.
            # - "explicit" - glob patterns can match explicit `.dot` patterns.
            check_dot_files: false
        
            # The point in the directory tree to start spell checking.
            # Default: .
            root: '.'
        
            # Notification level to use with inline reporting of spelling errors.
            # Allowed values are: warning, error, none
            # Default: warning
            inline: warning
        
            # Reports flagged / forbidden words as errors.
            # If true, errors will still be reported even if `inline` is "none"
            treat_flagged_words_as_errors: false
        
            # Generate Spelling suggestions.
            suggestions: false
        
            # Determines if the action should be failed if any spelling issues are found.
            # Allowed values are: true, false
            # Default: true
            strict: true
        
            # Limit the files checked to the ones in the pull request or push.
            incremental_files_only: true
        
            # Path to `cspell.json`
            #config: '.config/cspell.config.yaml'
        
            # Log progress and other information during the action execution.
            # Default: false
            verbose: false
        
            # Use the `files` setting found in the CSpell configuration instead of `input.files`.
            use_cspell_files: false
        
            # Set how unknown words are reported.
            # Allowed values are: all, simple, typos, flagged
            # Default: all
            report: all
